apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world
spec:
  template:
    spec:
      containers:
        - image: spring-hello-world-app:universe
          name: spring-hello-world-app
          imagePullPolicy: Never