apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-hello-world
  name: spring-boot-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
    spec:
      containers:
      - image: spring-hello-world-app:latest
        name: spring-hello-world-app
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-hello-world-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: spring-app-service
                port:
                  number: 80
            path: /hello
          - pathType: Prefix
            backend:
              service:
                name: spring-app-service
                port:
                  number: 80
            path: /fail
  # This section is only required if TLS is to be enabled for the Ingress
#  tls:
#    - hosts:
#        - www.example.com
#      secretName: example-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-app-service
  name: spring-app-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-boot-hello-world
  type: ClusterIP
